services:
###> doctrine/doctrine-bundle ###
  database:
    image: mysql:${MYSQL_VERSION:-8.0}
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-facturationApp}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-test}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-test}
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - "3306"
###< doctrine/doctrine-bundle ###

###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
###< symfony/mailer ###

###> sensiolabs/gotenberg-bundle ###
  gotenberg:
    image: 'gotenberg/gotenberg:8'
    ports:
      - "3000:3000"
###< sensiolabs/gotenberg-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
